DROP TABLE IF EXISTS player_events;
DROP TABLE IF EXISTS server_events;
DROP TABLE IF EXISTS server_settings;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS servers;